name: Deploy
on:
  workflow_run:
      workflows: 
        - Test 
      branches: 
        - main
      types:
        - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-python@v3
      with:
        python-version: 2.5.3
    - uses: Smatnemo/smatwebsite@main
      with:
        target: staging
        deploy_key: ${{ secrets.DEPLOY_ENC_KEY }}